### PR TITLE
russian translation

### LINKED ISSUE #46: Russian (Русский) <ru.cfg>
# Localization - ![Русский][RU] Russian (Русский) <ru.cfg>

## To Be Done by :octocat: contributor

* Some helpful reading
  * [Readme on localization][lclztn]
  * [Quickstart guide to localization][qs]
  * these should help guide you
  * both are in markdown {text}
  * if you are feeling very helpful, kindly translate these as well. ;P
* GameData (done by contributor)
  * [ ] add Localization\<ru.cfg> 🗃️
* Translation
  * [ ] ![Русский][RU] Russian (Русский) <ru.cfg>

1. Fork this repo
2. Create a branch name it 'translations' or localizations (suggestions)
3. goto `GameData/.../Localization/`
4. copy <en-us.cfg>
5. rename to <ru.cfg>
6. open the file and translate everything to the right of `#??? = `
7. change the `en-us` to `ru`
8. please include an attribution to you in the localization file, something like:
  * `// Translated by: [GitHubUserName](https://github.com/GitHubUserName)`
  * alternatively if you want another name from the KSP forums...
9. when done, PR it and you could reference this issue
10. After it has been merged by me, you may delete your fork.

have fun and thank you! :octocat: 🎃

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### below done by @zer0Kerbal

* Update
  * Documentation
    * [ ] [readme.md] 🔢
    * [ ] [release.md] 🧾
  * docs/
    * [ ] docs/[localization.md]
  * Update Social Media
  * [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
  * [x] CurseForge
  * [x] Reddit
  * [x] Twitter @zer0Kerbal
  * [x] Forum
  * [x] Patreon
  * [x] SpaceDock
  * [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[RU]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/RU.png "Русский"

this file: © All Rights Reserved by zer0Kerbal

### PR DESCRIPTION
**Pull request by evanisrael**
- Created ru.cfg file.

- Created ru translated versions of readme and quickstart also:) (named readme-ru and quickstart-ru respectively)

@zer0Kerbal

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
@evanisrael

> * Created ru.cfg file.
closes #46 

Plan is to publish a new release on Monday.

Spasibo, evanisrael

> * Created ru translated versions of readme and quickstart also:) (named readme-ru and quickstart-ru respectively)

😮 Wow, this is going above and beyond and is _very_ much appreciated. With your okay will add to all my addon repo's Localization directories.

Большое спасибо, Эванисраэль!

Finally - were the localization `readme` and `quickstart` understandable and useful?

**Review by zer0Kerbal — APPROVED** [review]
closes #46 

Spasibo @evanisrael

**Comment by evanisrael** [comment]
> Finally - were the localization `readme` and `quickstart` understandable and useful?

@zer0Kerbal glad I could help! Been a pleasure
And yes, it was clear and 100% useful👍

**Comment by zer0Kerbal** [comment]
@evanisrael 

👍 good to hear! 🌽

If you find some free time, or the itch to continue translating, [here is the link](https://github.com/users/zer0Kerbal/projects/34/views/1?filterQuery=-status%3ADone%2C%22Brazilian+%28pt-br%29%22%2C%22Dutch+%28nl-nl%29%22%2C%22French+%28Fran%C3%A7ais%29+%3Cfr-fr.cfg%3E%22%2C%22German+%28de-de%29%22%2C%22Italian+%28Italiano%29+%3Cit-it.cfg%3E%22%2C%22Japanese%28%E6%97%A5%E6%9C%AC%E8%AA%9E%29+%28ja.cfg%29%22%2C%22Korean+%28%ED%95%9C%EA%B5%AD%EC%96%B4%29+%3Cko.cfg%3E%22%2C%22Mexican+Spanish+%28Espa%C3%B1ol+Mexicano%29+%3Ces-mx.cfg%3E%22%2C%22Norwegian+%28Norsk%29+%3Cno-no.cfg%3E%22%2C%22Polish+%28Polski%29+%3Cpl.cfg%3E%22%2C%22Simplified+Chinese+%28%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%29+%3Czh-cn.cfg%3E%22%2C%22Spanish+%28Espa%C3%B1ol%29+es-es.cfg%22%2C%22Swedish+%28Svenska%29+%28sw-sw%29%22%2C%22Taiwanese+%28%E5%9B%BD%E8%AF%AD%29+%3Czh-tw.cfg%3E%22%2C%22Turkish+%28T%C3%BCrk%29+%3Ctr-tr.cfg%3E%22%2C%22In+Progress%22) to my localization project 😁 which has links to more KSP addons of mine that need Russian localization.

**Pull request merged**
